# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.9
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: 'Danny '
has_binder: false
has_settings: false
kind: theme
labextension_name: mytheme
project_short_description: A JupyterLab extension.
python_name: mytheme
repository: ''
test: false

